# Databricks notebook source
# Define the schema EA_Cost_Actual
schemaEaCostActual = StructType([
    StructField("InvoiceSectionName", StringType(), True),
    StructField("AccountName", StringType(), True),
    StructField("AccountOwnerId", StringType(), True),
    StructField("SubscriptionId", StringType(), True),
    StructField("SubscriptionName", StringType(), True),
    StructField("ResourceGroup", StringType(), True),
    StructField("ResourceLocation", StringType(), True),
    StructField("Date", DateType(), True),
    StructField("ProductName", StringType(), True),
    StructField("MeterCategory", StringType(), True),
    StructField("MeterSubCategory", StringType(), True),
    StructField("MeterId", StringType(), True),
    StructField("MeterName", StringType(), True),
    StructField("MeterRegion", StringType(), True),
    StructField("UnitOfMeasure", StringType(), True),
    StructField("Quantity", DoubleType(), True),
    StructField("EffectivePrice", DoubleType(), True),
    StructField("CostInBillingCurrency", DecimalType(18, 2), True),
    StructField("CostCenter", StringType(), True),
    StructField("ConsumedService", StringType(), True),
    StructField("ResourceId", StringType(), True),
    StructField("Tags", StringType(), True),
    StructField("OfferId", StringType(), True),
    StructField("AdditionalInfo", StringType(), True),
    StructField("ServiceInfo1", StringType(), True),
    StructField("ServiceInfo2", StringType(), True),
    StructField("ResourceName", StringType(), True),
    StructField("ReservationId", StringType(), True),
    StructField("ReservationName", StringType(), True),
    StructField("UnitPrice", StringType(), True),
    StructField("ProductOrderId", StringType(), True),
    StructField("ProductOrderName", StringType(), True),
    StructField("Term", StringType(), True),
    StructField("PublisherType", StringType(), True),
    StructField("PublisherName", StringType(), True),
    StructField("ChargeType", StringType(), True),
    StructField("Frequency", StringType(), True),
    StructField("PricingModel", StringType(), True),
    StructField("AvailabilityZone", StringType(), True),
    StructField("BillingAccountId", StringType(), True),
    StructField("BillingAccountName", StringType(), True),
    StructField("BillingCurrencyCode", StringType(), True),
    StructField("BillingPeriodStartDate", DateType(), True),
    StructField("BillingPeriodEndDate", DateType(), True),
    StructField("BillingProfileId", StringType(), True),
    StructField("BillingProfileName", StringType(), True),
    StructField("InvoiceSectionId", StringType(), True),
    StructField("IsAzureCreditEligible", StringType(), True),
    StructField("PartNumber", StringType(), True),
    StructField("PayGPrice", StringType(), True),
    StructField("PlanName", StringType(), True),
    StructField("ServiceFamily", StringType(), True),
    StructField("CostAllocationRuleName", StringType(), True),
    StructField("benefitId", StringType(), True),
    StructField("benefitName", StringType(), True)
])

# COMMAND ----------

# Define the schema EA_Prices
schemaEaPrices = StructType([
    StructField("EnrollmentNumber", IntegerType(), True),
    StructField("MeterID", StringType(), True),
    StructField("MeterName", StringType(), True),
    StructField("MeterType", StringType(), True),
    StructField("MeterCategory", StringType(), True),
    StructField("MeterSubCategory", StringType(), True),
    StructField("ServiceFamily", StringType(), True),
    StructField("Product", StringType(), True),
    StructField("SkuID", StringType(), True),
    StructField("ProductID", StringType(), True),
    StructField("MeterRegion", StringType(), True),
    StructField("UnitOfMeasure", StringType(), True),
    StructField("PartNumber", StringType(), True),
    StructField("EffectiveStartDate", StringType(), True),
    StructField("EffectiveEndDate", StringType(), True),
    StructField("UnitPrice", FloatType(), True),
    StructField("BasePrice", FloatType(), True),
    StructField("MarketPrice", FloatType(), True),
    StructField("CurrencyCode", StringType(), True),
    StructField("IncludedQuantity", StringType(), True),
    StructField("OfferID", StringType(), True),
    StructField("Term", StringType(), True),
    StructField("PriceType", StringType(), True)
])